Disable unit test

diff --git a/.github/workflows/build-cloudberry-rocky8.yml b/.github/workflows/build-cloudberry-rocky8.yml
--- a/.github/workflows/build-cloudberry-rocky8.yml
+++ b/.github/workflows/build-cloudberry-rocky8.yml
@@ -579,17 +579,17 @@ jobs:
             echo "- GCC Version: $(gcc --version | head -n1)"
           } >> "$GITHUB_STEP_SUMMARY"
 
-      - name: Run Apache Cloudberry configure script
-        if: needs.check-skip.outputs.should_skip != 'true'
-        env:
-          SRC_DIR: ${{ github.workspace }}
-        run: |
-          set -eo pipefail
-          chmod +x "${SRC_DIR}"/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh
-          if ! time su - gpadmin -c "cd ${SRC_DIR} && SRC_DIR=${SRC_DIR} ENABLE_DEBUG=${{ env.ENABLE_DEBUG }} ${SRC_DIR}/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh"; then
-            echo "::error::Configure script failed"
-            exit 1
-          fi
+#      - name: Run Apache Cloudberry configure script
+#        if: needs.check-skip.outputs.should_skip != 'true'
+#        env:
+#          SRC_DIR: ${{ github.workspace }}
+#        run: |
+#          set -eo pipefail
+#          chmod +x "${SRC_DIR}"/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh
+#          if ! time su - gpadmin -c "cd ${SRC_DIR} && SRC_DIR=${SRC_DIR} ENABLE_DEBUG=${{ env.ENABLE_DEBUG }} ${SRC_DIR}/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh"; then
+#            echo "::error::Configure script failed"
+#            exit 1
+#          fi
 
       - name: Run Apache Cloudberry build script
         if: needs.check-skip.outputs.should_skip != 'true'
